package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.BooleanEntry;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.StructPublisher;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Robot;
import frc.robot.constants.PoseConstants;
import frc.robot.constants.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.utils.Container;
import frc.robot.utils.LimelightHelpers;
import frc.robot.utils.ShooterCalculator;
import frc.robot.utils.SwerveFieldContactSim;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.001; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;
    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();
    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    // Limelight runtime toggles exposed via NetworkTables for quick driver-station control.
    private NetworkTable llTable = NetworkTableInstance.getDefault().getTable("LL");
    private BooleanEntry llTurretEnabledEntry = llTable.getBooleanTopic("LL-Turret_Enabled").getEntry(true);
    private BooleanEntry llFixedEnabledEntry = llTable.getBooleanTopic("LL-Fixed_Enabled").getEntry(true);
    private BooleanEntry disabledLocoEnabledEntry = llTable.getBooleanTopic("DisabledLocoEnabled").getEntry(true);

    // Dashboard chooser used while disabled to select autonomous start pose.
    private final SendableChooser<String> startPoseChooser = new SendableChooser<>();
    private Pose2d initialStartPose2d = new Pose2d(0, 0, new Rotation2d());



    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    @SuppressWarnings("unused")
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    @SuppressWarnings("unused")
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
        setStartPoseInitial();
        SmartDashboard.putData("Conf/Field", field);
    }


    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        setStartPoseInitial();
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    public Pose2d getPose() {
        return getState().Pose;
    }

    /**
     * Returns shooter-reference distance (meters) from current robot pose to alliance hub target.
     */
    public double getDistanceToHub() {
        return ShooterCalculator.getDistanceToHub(getPose());
    }



    private Field2d field = new Field2d();

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        updateStartConditions();

        if(Robot.isReal()) visionPeriodic();

        field.setRobotPose(getPose());

        
    }

    public StructPublisher<Pose2d> posePublisher = NetworkTableInstance.getDefault()
            .getStructTopic("Sim/SwervePose", Pose2d.struct)
            .publish();

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;
            posePublisher.set(getState().Pose);
            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    private boolean isSimulationInitialized = false;
    
    @Override
    public void simulationPeriodic() {

        if(!isSimulationInitialized)
        {
            m_lastSimTime = Utils.getCurrentTimeSeconds();
            isSimulationInitialized = true;
            return;
        }

        final double currentTime = Utils.getCurrentTimeSeconds();
        double deltaTime = currentTime - m_lastSimTime;
        m_lastSimTime = currentTime;
        posePublisher.set(getState().Pose);
        /* use the measured time delta, get battery voltage from WPILib */
        updateSimState(deltaTime, RobotController.getBatteryVoltage());
        SwerveFieldContactSim.getInstance().handleSwerveSimFieldCollisions();
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            // PathPlanner wiring: pose/speed suppliers + robot-relative output consumer.
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(10, 0, 0),
                    // PID constants for rotation
                    new PIDConstants(7, 0, 0)
                ),
                config,
                // Manual path flip is handled elsewhere in this codebase.
                () -> {return !Container.isBlue;},
                this // Subsystem for requirements
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }

    public void setStartPoseInitial()
    {
        // Start-pose options shown on dashboard during disabled.
        startPoseChooser.addOption("RIGHT", "RIGHT");
        startPoseChooser.addOption("MIDDLE", "MIDDLE");
        startPoseChooser.setDefaultOption("LEFT", "LEFT");
    
        SmartDashboard.putData("Conf/StartPoseChooser", startPoseChooser); // SendableChooser requires SmartDashboard.putData

        // Seed odometry to alliance-appropriate default start pose.
        if(!Container.isBlue){
            initialStartPose2d = PoseConstants.START_POSE_RED_LEFT;
            resetPose(initialStartPose2d);
        }
        else{
            initialStartPose2d = PoseConstants.START_POSE_BLUE_LEFT;
            resetPose(initialStartPose2d);
        }

        // Default all vision sources to enabled at startup.
        llTurretEnabledEntry.set(true);
        llFixedEnabledEntry.set(true);
        disabledLocoEnabledEntry.set(true);
    }

    public Pose2d getInitialStartPose()
    {
        return initialStartPose2d;
    }

    public void setStartPose()
    {
        resetPose(initialStartPose2d);
    }

    public ChassisSpeeds getSpeeds()
    {
        return getState().Speeds;
    }

    public ChassisSpeeds getFieldSpeeds()
    {
        return ChassisSpeeds.fromRobotRelativeSpeeds(
            getState().Speeds,
            getPose().getRotation()
        );
    }

    public void updateStartConditions()
     {
        // Pose selection is only allowed while disabled to avoid odometry jumps in-match.
        if(!DriverStation.isDisabled()) return;

        String selectedStartPose = startPoseChooser.getSelected();
        Pose2d selectedPose;
            if (!Container.isBlue) {
                switch (selectedStartPose) {
                    case "LEFT":
                        selectedPose = PoseConstants.START_POSE_RED_LEFT;
                        break;
                    case "MIDDLE":
                        selectedPose = PoseConstants.START_POSE_RED_MIDDLE;
                        break;
                    case "RIGHT":
                        selectedPose = PoseConstants.START_POSE_RED_RIGHT;
                        break;
                    default:
                        selectedPose = initialStartPose2d;
                        break;
                }
            } else {
                switch (selectedStartPose) {
                    case "LEFT":
                        selectedPose = PoseConstants.START_POSE_BLUE_LEFT;
                        break;
                    case "MIDDLE":
                        selectedPose = PoseConstants.START_POSE_BLUE_MIDDLE;
                        break;
                    case "RIGHT":
                        selectedPose = PoseConstants.START_POSE_BLUE_RIGHT;
                        break;
                    default:
                        selectedPose = initialStartPose2d;
                        break;
                }
                
            }

            if(selectedPose != initialStartPose2d)
            {
                initialStartPose2d = selectedPose;
                resetPose(initialStartPose2d);
            }
     }

    public double getHeading() {
        double yawDeg = getPose().getRotation().getDegrees() % 360;
        if (yawDeg < 0) {
            yawDeg += 360;
        }
        return yawDeg;
    }

    public double getGyroRate() {
        return getState().Speeds.omegaRadiansPerSecond * (180.0 / Math.PI);
    }

    LimelightHelpers.IMUData imuData;
    private static final Matrix<N3, N1> MT2_VISION_STD_DEVS = VecBuilder.fill(.6, .6, 9999999);
    private static final Matrix<N3, N1> MT1_VISION_STD_DEVS = VecBuilder.fill(.5, .5, 9999999);
    private double tempRobotYaw = 0.0;
    private LimelightHelpers.PoseEstimate tempLimelightMeasurementTurret;
    private LimelightHelpers.PoseEstimate tempLimelightMeasurementFixed;
    private boolean tempDoRejectUpdate = false;
    private boolean tempDoRejectTurret = false;
    private boolean tempDoRejectFixed = false;
    public void addVisionMeasurementMT2() {
        // Keep Limelight orientation aligned with drivetrain heading.
        tempRobotYaw = getHeading();
        LimelightHelpers.SetRobotOrientation_NoFlush("limelight-turret", tempRobotYaw, 0.0, 0.0, 0.0, 0.0, 0.0);
        LimelightHelpers.SetRobotOrientation("limelight-normal", tempRobotYaw, 0.0, 0.0, 0.0, 0.0, 0.0);

        imuData = LimelightHelpers.getIMUData("limelight-turret");

    // Gather both camera estimates (turret camera + fixed camera).
    tempLimelightMeasurementTurret = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-turret");
    tempLimelightMeasurementFixed = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2("limelight-normal");

    tempDoRejectUpdate = false;
    tempDoRejectTurret = false;
    tempDoRejectFixed = false;


        
        if(Math.abs(getGyroRate()) > 360)
        {
            tempDoRejectUpdate = true;
        }


        //if(drivetrain.swerveDataSupplier().get().swerveControlState == SwerveState.AIMING) doRejectUpdate = true;

        if(tempLimelightMeasurementTurret != null)
        {
        if(tempLimelightMeasurementTurret.tagCount == 0)
            {
                tempDoRejectTurret = true;
            }
        if(Math.abs(imuData.accelZ) > 120.0)
            {
                tempDoRejectTurret = true;
            }
        }
        else tempDoRejectTurret = true;

        if(tempLimelightMeasurementFixed != null)
        {
        if(tempLimelightMeasurementFixed.tagCount == 0)
            {
                tempDoRejectFixed = true;
            }
        }
        else tempDoRejectFixed = true;


    // Apply accepted measurements with conservative heading trust.
    if(!tempDoRejectUpdate)
        {
            if(!tempDoRejectTurret && llTurretEnabledEntry.get(true))
            {
                setVisionMeasurementStdDevs(MT2_VISION_STD_DEVS);
                addVisionMeasurement(
                tempLimelightMeasurementTurret.pose,
                tempLimelightMeasurementTurret.timestampSeconds
                );
            }

            if(!tempDoRejectFixed && llFixedEnabledEntry.get(true))
            {
                setVisionMeasurementStdDevs(MT2_VISION_STD_DEVS);
                addVisionMeasurement(
                tempLimelightMeasurementFixed.pose,
                tempLimelightMeasurementFixed.timestampSeconds
                );
            }
        }
    }

    public void addVisionMeasurementMT1() {
        // Keep Limelight orientation aligned with drivetrain heading.
    tempRobotYaw = getHeading();
    LimelightHelpers.SetRobotOrientation_NoFlush("limelight-turret", tempRobotYaw, 0.0, 0.0, 0.0, 0.0, 0.0);
    LimelightHelpers.SetRobotOrientation("limelight-normal", tempRobotYaw, 0.0, 0.0, 0.0, 0.0, 0.0);

    // Gather both camera estimates (legacy solve path).
    tempLimelightMeasurementTurret = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-turret");
    tempLimelightMeasurementFixed = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-normal");

    tempDoRejectUpdate = false;
    tempDoRejectTurret = false;
    tempDoRejectFixed = false;

    
    if(Math.abs(getGyroRate()) > 360)
    {
        tempDoRejectUpdate = true;
    }

    if(tempLimelightMeasurementTurret != null)
    {
        if(tempLimelightMeasurementTurret.tagCount < 1)
            {
                tempDoRejectTurret = true;
            }

        if(tempLimelightMeasurementTurret.avgTagDist > 3.5)
            {
                tempDoRejectTurret = true;
            }
    }
    else tempDoRejectTurret = true;

    if(tempLimelightMeasurementFixed != null)
    {
    if(tempLimelightMeasurementFixed.tagCount < 1)
        {
            tempDoRejectFixed = true;
        }
        if(tempLimelightMeasurementFixed.avgTagDist > 3.5)
            {
                tempDoRejectFixed = true;
            }
    }
    else tempDoRejectFixed = true;


    if(!tempDoRejectUpdate)
    {
        if(!tempDoRejectTurret && llTurretEnabledEntry.get(true))
        {
            setVisionMeasurementStdDevs(MT1_VISION_STD_DEVS);

            addVisionMeasurement(
            tempLimelightMeasurementTurret.pose,
            tempLimelightMeasurementTurret.timestampSeconds
            );
        }

        if(!tempDoRejectFixed && llFixedEnabledEntry.get(true))
        {
            setVisionMeasurementStdDevs(MT1_VISION_STD_DEVS);
            addVisionMeasurement(
            tempLimelightMeasurementFixed.pose,
            tempLimelightMeasurementFixed.timestampSeconds
            );
        }
    }
    }

    public void resetWithMT1()
    {
        // Prefer fixed camera reset; fall back to turret camera if needed.
        tempRobotYaw = 0;

        tempLimelightMeasurementFixed = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-normal");

        if(tempLimelightMeasurementFixed != null && tempLimelightMeasurementFixed.tagCount > 0)
        {
            if (tempLimelightMeasurementFixed.avgTagDist < 3.0) {
                resetPose(tempLimelightMeasurementFixed.pose);
                tempRobotYaw = tempLimelightMeasurementFixed.pose.getRotation().getDegrees();
            }
        }
        else
        {
            tempLimelightMeasurementTurret = LimelightHelpers.getBotPoseEstimate_wpiBlue("limelight-turret");
            if(tempLimelightMeasurementTurret != null && tempLimelightMeasurementTurret.tagCount > 0)
                {
                    if (tempLimelightMeasurementTurret.avgTagDist < 3.0) {
                        resetPose(tempLimelightMeasurementTurret.pose);
                        tempRobotYaw = tempLimelightMeasurementTurret.pose.getRotation().getDegrees();

                    }
                }
        }
        
        LimelightHelpers.SetRobotOrientation_NoFlush("limelight-turret", tempRobotYaw, 0.0, 0.0, 0.0, 0.0, 0.0);
        LimelightHelpers.SetIMUMode("limelight-turret", 1);
  
        
        LimelightHelpers.SetRobotOrientation("limelight-normal", tempRobotYaw, 0.0, 0.0, 0.0, 0.0, 0.0);
        LimelightHelpers.SetIMUMode("limelight-normal", 1);
    }

    private boolean isMode1Set = false;
    private boolean isLLReady = false;

    public void disabledPeriodic()
    {
        // In disabled, optionally relocalize continuously for cleaner autonomous starts.
        isMode1Set = true;

        if (disabledLocoEnabledEntry.get(true)) {
            resetWithMT1();
        }
    }

    public void enabledPeriodic()
    {   
        // On first enable after disabled, switch LL IMU mode for in-match tracking.
        if(!isLLReady && isMode1Set)
        {
            tempRobotYaw = getPose().getRotation().getDegrees();


            LimelightHelpers.SetRobotOrientation_NoFlush("limelight-turret", tempRobotYaw, 0.0, 0.0, 0.0, 0.0, 0.0);
            LimelightHelpers.SetIMUMode("limelight-turret", 0);
    
            
            LimelightHelpers.SetRobotOrientation("limelight-normal", tempRobotYaw, 0.0, 0.0, 0.0, 0.0, 0.0);
            LimelightHelpers.SetIMUMode("limelight-normal", 0);
            isLLReady = true;
        }

        // Once ready, fuse MegaTag2 vision each periodic call.
        if(isLLReady) addVisionMeasurementMT2();
    }

    private boolean isEnabled = false;
    // Vision sampling: run vision-heavy work once every VISION_LOOPS scheduler loops
    private int visionLoopCounter = 0;
    private static final int VISION_LOOPS = 4; // ~10Hz at 20ms loop; tune as needed
    // Disabled relocalization can be expensive over NT; run at a lower cadence.
    private int disabledVisionLoopCounter = 0;
    private static final int DISABLED_VISION_LOOPS = 10; // ~5Hz at 20ms loop

    public void visionPeriodic()
    {
        boolean wasEnabled = isEnabled;
        if (DriverStation.isEnabled() && !isEnabled) {
            // rising edge: mark enabled
            isEnabled = true;
        }
        if (DriverStation.isDisabled() && isEnabled) {
            // falling edge: clear flags
            isEnabled = false;
            isLLReady = false;
            disabledVisionLoopCounter = DISABLED_VISION_LOOPS;
        }

        if (isEnabled) {
            if (!wasEnabled) {
                // Just became enabled — run the enabledPeriodic once immediately to initialize Limelight state
                enabledPeriodic();
                visionLoopCounter = 0;
            } else {
                // Rate-limit expensive vision processing to reduce loop jitter.
                visionLoopCounter++;
                if (visionLoopCounter >= VISION_LOOPS) {
                    visionLoopCounter = 0;
                    enabledPeriodic();
                }
            }
        } else {
            // Disabled loop can be expensive due to relocalization + LL config writes.
            // Keep periodic lightweight by throttling to a slower cadence.
            disabledVisionLoopCounter++;
            if (disabledVisionLoopCounter >= DISABLED_VISION_LOOPS) {
                disabledVisionLoopCounter = 0;
                disabledPeriodic();
            }
        }
    }

    public InstantCommand resetPoseWithMT1Command()
     {
         return new InstantCommand(() -> 
        {
            resetWithMT1();
        });
     }

    public boolean isRobotOnLeftSide()
    {
        // Side logic is mirrored by alliance.
        if(Container.isBlue)
        {
            return (getPose().getY() > 4.0);
        }
        else
        {
            return (getPose().getY() < 4.0);
        }
    }

    public boolean isRobotOnTheShootingZone()
    {
        // Shooting-zone boundary is mirrored by alliance.
        if(Container.isBlue)
        {
            return (getPose().getX() < 4.45);
        }
        else
        {
            return (getPose().getX() > 12);
        }
    }
}