// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.commands;

import com.pathplanner.lib.auto.AutoBuilder;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.ParallelCommandGroup;
import frc.robot.TheMachine;
import frc.robot.constants.DriveConstants;
import frc.robot.subsystems.CommandSwerveDrivetrain;

/**
 * Pathfinds the robot to a midfield staging pose while retracting mechanisms.
 */
/* You should consider using the more terse Command factories API instead https://docs.wpilib.org/en/stable/docs/software/commandbased/organizing-command-based.html#defining-commands */
public class GoToMidCommand extends ParallelCommandGroup {

  /** Creates a new GoToNeutralFromTrenchCommand. */
  public GoToMidCommand(CommandSwerveDrivetrain drivetrain, TheMachine theMachine) {
    // Drive motion command generated by PathPlanner AutoBuilder.
    Command builtCommand = AutoBuilder.pathfindToPose(new Pose2d(8,4, new Rotation2d(Math.toRadians(90))),
                                                     DriveConstants.PATH_CONSTRAINTS_FOLLOW_PATH);

    // Run machine transition in parallel so mechanism state is ready on arrival.
    InstantCommand theMachineCommand = new InstantCommand(() -> theMachine.idleRetracted());
    addRequirements(theMachine.getSubsystems());
    addCommands(builtCommand, theMachineCommand);
  }

}
